on:
  push:
    branches: [ "main" , "master" ]

  workflow_dispatch:
  
jobs:
  docker:
    uses: GBADsInformatics/DevopsWorkflows/.github/workflows/docker.yml@main
    secrets: inherit
    with:
      IMAGE_NAME: apiui

  aws:
    needs: docker
    uses: GBADsInformatics/DevopsWorkflows/.github/workflows/aws.yml@main
    secrets: inherit
    with:
      SERVICE_NAME: apiui-dash-service
