on:
  push:
    branches: [ "main" , "master" ]

  workflow_dispatch:
  
jobs:
  commit-hash:
    name: Commit SHA
    runs-on: ubuntu-latest
    outputs:
      sha7: ${{ steps.commit-hash.outputs.sha7 }}
    steps:
      - name: Get Commit SHA
        id: commit-hash
        run: echo "sha7=$(echo ${GITHUB_SHA} | cut -c1-7)" >> "$GITHUB_OUTPUT"

  docker:
    uses: GBADsInformatics/DevopsWorkflows/.github/workflows/docker.yml@v2.0
    secrets: inherit
    with:
      IMAGE_NAME: apiui

  aws:
    needs: [commit-hash, docker]
    uses: GBADsInformatics/DevopsWorkflows/.github/workflows/aws.yml@v2.0
    secrets:
      template-input: >-
        ApplicationName=api-ui-dash,
        DockerURI=gbadsinformatics/apiui:${{ needs.commit-hash.outputs.sha7 }},
        BaseURL=/dashboards/apiui,
        ListenerRulePriority=18
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    with:
      stack-name: api-ui-dash-stack
      template-inputs: >-
        ApplicationName=api-ui-dash,
        DockerURI=gbadsinformatics/apiui:${{ needs.commit-hash.outputs.sha7 }},
        BaseURL=/dashboards/apiui,
        ListenerRulePriority=18
